name: "GitHub Actions"
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: crowdly_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev

      - name: Prepare Database
        run: |
          rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: "postgres://rails:password@localhost:5432/crowdly_test"
        run: |
          rails test
